name: zapchat_design
description: "A new Flutter package project."
version: 0.0.1
homepage: null

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  gap: ^3.0.1

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.

flutter:
  fonts:
    - family: Courier-Prime
      fonts:
        - asset: fonts/Courier-Prime.ttf
    - family: Inter
      fonts:
        - asset: fonts/Inter.ttc
    - family: Lora
      fonts:
        - asset: fonts/Lora[wght].ttf
   
          
       
